name: Build the blog

on:
  push:
    branches:
      - main
    paths:
      - 'write/**'
      - 'assets/**'
      - 'bw.sh'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get files in gh-pages
        run: | 
          if git ls-remote --exit-code --heads origin gh-pages; then
            git fetch origin gh-pages

            check_item=(
              checksum/
              posts/
              tags/
              all-posts.html
              all-tags.html
            )
            for item in "${check_item[@]}"; do
              
              if git ls-tree -r origin/gh-pages --name-only | grep -q "^$item"; then
                git checkout origin/gh-pages -- $item
              fi
            done    
          fi
          
      - name: Build
        run: |
          chmod +x bw.sh
          ./bw.sh b

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 
        with:
          path: .
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
