name: Build the blog

on:
  push:
    branches:
      - main
    paths:
      - 'write/**'
      - 'assets/**'
      - 'bw.sh'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # The script retrieves previously created files from the gh-pages branch to avoid doing the same work twice.
      - name: Build
        run: |
          chmod +x bw.sh

          if git ls-remote --exit-code --heads origin gh-pages; then
            git fetch origin gh-pages
            git checkout gh-pages -- checksum
            
            echo '++++++ ls'
            ls
            echo '++++++ cksum'
            cksum bw.sh
            echo '++++++ cksum_script'
            cat checksum/cksum_script.txt
            echo '++++++'
            
            
            ./bw.sh b
          else
            ./bw.sh b
          fi
          
      - name: gh-pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
